name: Scan SonarCloud
on:
  workflow_call:
    inputs:
      php-version:
        description: "PHP Version"
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_ORGANIZATION:
        required: true
      SONAR_PROJECT:
        required: true
jobs:
  sonarcloud:
    name: Scan SonarCloud Job
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Laravel App
        uses: ./.github/prepare-action
        with:
          php-version: ${{ inputs.version }}
          cache-key: ${{ github.sha }}-php-vendor-cache
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.verbose=true
